version: "2"

services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "discovery"
  es:
    image: elasticsearch:7.17.19
    container_name: es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  memcached:
    image: memcached:1.6
    container_name: memcached
  discovery:
    # Uncomment this line to use the official course-discovery base image
    image: edxops/discovery:latest

    # Uncomment the next two lines to build from a local configuration repo
    # build: ../configuration/docker/build/discovery/

    container_name: discovery
    volumes:
      - ..:/edx/app/discovery/discovery
      - /edx/app/discovery/discovery/node_modules
      - ../course_discovery/media:/edx/var/discovery/media
      - ../course_discovery/assets:/edx/var/discovery/staticfiles
    command: tail -f /dev/null
    depends_on:
      - "mysql80"
      - "es"
      - "memcached"
    environment:
      CACHE_BACKEND: "django.core.cache.backends.memcached.PyMemcacheCache"
      CACHE_LOCATION: "memcached:11211"
      CONN_MAX_AGE: 60
      DB_ENGINE: "django.db.backends.mysql"
      DB_NAME: "discovery"
      DB_PASSWORD: "password"
      DB_PORT: "3306"
      DB_USER: "root"
      DJANGO_SETTINGS_MODULE: "course_discovery.settings.test"
      ENABLE_DJANGO_TOOLBAR: 1
      TEST_ELASTICSEARCH_URL: "http://es:9200"

volumes:
  elasticsearch_data:
    driver: local
